# Use the base Redis image
FROM redis:latest
#RUN apt-get update && apt-get install -y wget build-essential
#RUN wget https://github.com/RedisAI/RedisAI/releases/download/v1.2.7/redisai.so -O /usr/local/lib/redisai.so
#CMD ["redis-server", "--loadmodule", "/usr/local/lib/redisai.so"]
