FROM redis:latest
#COPY entrypoint.sh /entrypoint.sh
#RUN chmod +x entrypoint.sh
#CMD ["/entrypoint.sh"]
#COPY sysctl.conf /etc/sysctl.conf
#COPY entrypoint.sh /usr/local/bin/entrypoint.sh
#RUN chmod +x /usr/local/bin/entrypoint.sh
#ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
#CMD ["redis-server"]
