version: '3.6'

services:

    redis:
        image: redis:latest
        ports:
          - 6379:6379
        networks:
          - my-network
        hostname: redis
        volumes:
          - redis-data:/data
        command: redis-server
        mem_limit: 7G

    api:
        depends_on:
            - mysql
            - redis
        container_name: my_api
        build:
            context: C:/dev/broker/services/api
            dockerfile: Dockerfile
        restart: on-failure
        ports:
        - "5057:5057"
        working_dir: /app
        volumes:
            - C:/dev/broker/services/api/api.py:/app/api.py
        #command: 
        #    python api.py
        networks:
            - my-network

    worker: 
        build: #satish was here
            context: C:/dev/broker/services/worker
            dockerfile: Dockerfile
        restart: on-failure
        working_dir: /app
        #command: /bin/sh -c "sleep 5 && rq worker --url redis://redis:6379 my_queue"
        volumes: 
             #- ./:/app
             - ./:/app
        depends_on:
            - mysql
            - redis
        networks:
            - my-network

    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 7+WCy76_2$%g
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            - C:/dev/broker/services/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - my-network

volumes:
    mysql-data:
    redis-data:

networks:
    my-network:    
        driver: bridge