apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      restartPolicy: OnFailure # Add this line
      containers:
        - name: backend
          image: billin19/backend:latest
          ports:
            - containerPort: 5057
          resources:
            requests:
              cpu: 1000m
              memory: 2000Mi
            limits:
              cpu: 5000m
              memory: 10000Mi
