apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/disks/ssd2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: billin19/worker:latest
          volumeMounts:
            - name: worker-volume
              mountPath: /app/models
      volumes:
        - name: worker-volume
          persistentVolumeClaim:
            claimName: worker-pvc
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
