version: '3.6'

services:

    redis:
        image: redis:latest
        ports:
          - 6379:6379
        networks:
          - my-network
        hostname: redis
        volumes:
          #  - redis-data:/data
          - ./790:/redis
        command: redis-server #./redis/redis.conf    
        #command: python worker.py
        mem_limit: 7G
        #redis-server #
  

    myproj_api:
        depends_on:
            - mysql
            - redis
        container_name: my_api
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: on-failure
        ports:
        - "5057:5057"
        working_dir: /app
        volumes:
            - ./:/app
            #- ./:/app/tasks
           # - ./:/app
        command: 
            python api.py
        networks:
            - my-network

    myproj_worker: 
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: on-failure
        working_dir: /app
        #command: rq worker --url redis://redis:6379 my_queue
        command: /bin/sh -c "sleep 10 && rq worker --url redis://redis:6379 my_queue"
        #command: python worker.py
        volumes: 
             - ./:/app
        #command: python worker.py
        depends_on:
            - mysql
            - redis
        networks:
        - my-network

    mysql:
        container_name: mysql
        image: mysql:latest
        environment:
            #MYSQL_ROOT_PASSWORD: god
            MYSQL_ROOT_PASSWORD: 7+WCy76_2$%g
        ports:
        - "3307:3306"
        volumes:
        - mysql-data:/var/lib/mysql
        - ./my.cnf:/etc/mysql/my.cnf
        networks:
        - my-network

volumes:
    mysql-data:

networks:
    my-network:    
        driver: bridge