apiVersion: batch/v1
kind: Job
metadata:
  name: database
spec:
  template:
    spec:
      containers:
        - name: rollout
          image: billin19/jobs:latest
          command: ["python", "Database.py"]
      restartPolicy: Never
