apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: broker.local
      http:
        paths:
          - pathType: Prefix
            path: "/data"
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/public"
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/backend"
            backend:
              service:
                name: backend-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
