apiVersion: batch/v1
kind: Job
metadata:
  name: rollout
spec:
  template:
    spec:
      containers:
        - name: rollout
          image: localhost:5000/jobs:latest
          command: ["python", "app/rollout.py"]
      restartPolicy: Never
