apiVersion: batch/v1
on: [push]
kind: Job
metadata:
  name: rollout
spec:
  template:
    spec:
      containers:
        - name: rollout
          image: your-repo/python-script:latest
          command: ["python", "app/rollout.py"]
      restartPolicy: Never
