apiVersion: batch/v1
kind: Job
metadata:
  name: rollout
spec:
  template:
    spec:
      containers:
        - name: rollout
          image: billin19/jobs:latest
          command: ["python", "rollout.py"]
      restartPolicy: Never
