# .air.toml

# Configuring the air tool
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = ["*_test.go"]
  exclude_regex = ["^_"]

[log]
  level = "debug"
  color = "true"
  timestamp = "true"

[run]
  cmd = "./tmp/main"
  watch_delay = 1000
  grace_time = 1000
  output = "air.log"

