# Dockerfile.dev
FROM golang:1.22-alpine
RUN apk add --no-cache git
RUN go install github.com/cosmtrek/air@latest
WORKDIR /app
COPY go.mod go.sum ./

RUN go mod download

COPY . .
ENV IN_CONTAINER=true

EXPOSE 5057

#CMD ["air", "-c", ".air.toml"]
CMD ["air"]

