# Dockerfile.dev
FROM golang:1.22-alpine
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV IN_CONTAINER=true
EXPOSE 5057
ENTRYPOINT ["air","-c",".air.toml"]

