version: '3.6'

services:

#    frontend:
#        build:
#            context: /home/aj/dev/broker/services/frontend
#            dockerfile: Dockerfile
#        volumes: 
#          - /home/aj/dev/broker/services/frontend/:/app/
#        restart: always
#        ports:
#        - "5173:5173"
#        expose: 
#          - 5173

    tf:
        build:
            context: /home/aj/dev/broker/services/tf
            dockerfile: Dockerfile
        restart: always
        ports:
        - "8501:8501"
        - "8500:8500"
        volumes:
            - tf:/models
        networks:
          - compose_network

    backend:
        depends_on:
            - db
            - cache
        build:
            context: /home/aj/dev/broker/services/backend
            dockerfile: Dockerfile.dev
        restart: always
        ports:
        - "5057:5057"
        volumes:
            - /home/aj/dev/broker/services/backend/:/app
        networks:
            - compose_network

    ml: 
        build: #satish was here
            context: /home/aj/dev/broker/services/ml
            dockerfile: Dockerfile.dev
        depends_on:
            - db
            - cache
        networks:
            - compose_network
        volumes:
          - tf:/models
          - /home/aj/dev/broker/services/ml:/app
    db:
        build:
           context: /home/aj/dev/broker/services/db
           dockerfile: Dockerfile
        volumes:
           - db:/var/lib/postgresql/data
           - /home/aj/dev/broker/services/db/quotes:/postgres-data/quotes
        ports:
          - "5432:5432"
        networks:
            - compose_network
    cache:
        build:
            context: /home/aj/dev/broker/services/cache
            dockerfile: Dockerfile
        ports:
          - 6379:6379
        networks:
          - compose_network
        hostname: redis
        volumes:
          - cache:/data
        command: redis-server
        mem_limit: 12G
volumes:
    db:
    cache:
    tf:

networks:
    compose_network:    
        driver: bridge


