apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: myproj-api
  name: myproj_api
spec:
  ports:
    - name: "5057"
      port: 5057
      targetPort: 5057
  selector:
    io.kompose.service: myproj-api
status:
  loadBalancer: {}
