FROM python:3.10.1-bullseye
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
RUN pip install watchdog
COPY . .
RUN rm -rf venv
ENV PYTHONBUFFERED=1
#RUN rm -rf /app/models
#CMD ["python", "worker.py"]
CMD ["watchmedo", "auto-restart", "--recursive", "--patterns=*py", "--", "python", "-u", "worker.py"]


