apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.network/deployment-my-network: "true"
    io.kompose.service: worker
  name: worker
spec:
  containers:
    - args:
        - /bin/sh
        - -c
        - sleep 5 && rq worker --url redis://redis:6379 my_queue
      image: worker
      name: worker
      resources: {}
      volumeMounts:
        - mountPath: /app
          name: worker-claim0
      workingDir: /app
  restartPolicy: OnFailure
  volumes:
    - name: worker-claim0
      persistentVolumeClaim:
        claimName: worker-claim0
status: {}
