name: Unit Tests on Merge

on:
  pull_request:
    branches:
      - dev-master
      - prod-beta
      - prod-release
  push:
    branches:
      - dev-master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run test script
      run: python deployment/dev/test.py