name: Python Unit Tests on Merge

on:
  pull_request:
    branches:
      - none
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run test script
      run: python deployment/test.py

    - name: Rebuild and Push Docker images
      run: |
        docker build -t billin19/frontend:latest /services/frontend
        docker build -t billin19/backend:latest /services/backend
        docker build -t billin19/worker:latest /services/worker
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push billin19/frontend:latest
        docker push billin19/backend:latest
        docker push billin19/worker:latest

    - name: Apply Kubernetes YAMLs
      run: kubectl apply -f deployment/prod

    - name: Run transfer script
      run: python deployment/transfer.py
