name: Pull Request Description

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate pull request description
        uses: octue/generate-pull-request-description@1.0.0.beta-2
        with:
          # You may need to provide additional inputs as required by the action
          token: ${{ secrets.GITHUB_TOKEN }}
