name: Create Issue on Push to Main

on:
  push:
    branches:
      - none

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue using REST API
        uses: actions/github-script@v5
        with:
          script: |
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "New push to main",
              body: "A new push was made to the main branch. Here's what needs to be done next...",
            };
            github.rest.issues.create(issue);